// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6oG36vr7d4snAFIV0x95aq02pNGvdul0',
    appId: '1:318374626413:android:6e2287335824c80052ab64',
    messagingSenderId: '318374626413',
    projectId: 'afghan-in-usa',
    storageBucket: 'afghan-in-usa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPNQP5Gfa_3ZmHFZTkql86RnqTbYcDYPo',
    appId: '1:318374626413:ios:98860c6aa41ede3452ab64',
    messagingSenderId: '318374626413',
    projectId: 'afghan-in-usa',
    storageBucket: 'afghan-in-usa.firebasestorage.app',
    iosBundleId: 'com.afghaninusa',
    iosClientId: '318374626413-b1fjdi0qa5c13gtiva2ov17olvss79r1.apps.googleusercontent.com',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQSixVJF7KugGqNlkvuA2Xt0lUz-tt7aw',
    appId: '1:318374626413:web:8399c275007c95c052ab64',
    messagingSenderId: '318374626413',
    projectId: 'afghan-in-usa',
    authDomain: 'afghan-in-usa.firebaseapp.com',
    storageBucket: 'afghan-in-usa.firebasestorage.app',
  );
}
